//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr.etda.or.th
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InquiryPersonnelNewInfoRS", Namespace="http://tempuri.org/")]
    public partial class InquiryPersonnelNewInfoRS : object
    {
        
        private hr.etda.or.th.PersonnelNewInfo[] listPersonnelNewInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public hr.etda.or.th.PersonnelNewInfo[] listPersonnelNewInfo
        {
            get
            {
                return this.listPersonnelNewInfoField;
            }
            set
            {
                this.listPersonnelNewInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonnelNewInfo", Namespace="http://tempuri.org/")]
    public partial class PersonnelNewInfo : object
    {
        
        private string prefixTHField;
        
        private string prefixENField;
        
        private string staffNameTHField;
        
        private string staffSurnameTHField;
        
        private string staffNameENField;
        
        private string staffSurnameENField;
        
        private string nickNameField;
        
        private string staffIDField;
        
        private string depNameTHField;
        
        private string segNameTHField;
        
        private string positionNameTHField;
        
        private string depNameENField;
        
        private string segNameENField;
        
        private string positionNameENField;
        
        private string mobileField;
        
        private string telephoneField;
        
        private string startDTField;
        
        private string endDTField;
        
        private string fullNameTHField;
        
        private string fullNameENField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string prefixTH
        {
            get
            {
                return this.prefixTHField;
            }
            set
            {
                this.prefixTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prefixEN
        {
            get
            {
                return this.prefixENField;
            }
            set
            {
                this.prefixENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string staffNameTH
        {
            get
            {
                return this.staffNameTHField;
            }
            set
            {
                this.staffNameTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string staffSurnameTH
        {
            get
            {
                return this.staffSurnameTHField;
            }
            set
            {
                this.staffSurnameTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string staffNameEN
        {
            get
            {
                return this.staffNameENField;
            }
            set
            {
                this.staffNameENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string staffSurnameEN
        {
            get
            {
                return this.staffSurnameENField;
            }
            set
            {
                this.staffSurnameENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nickName
        {
            get
            {
                return this.nickNameField;
            }
            set
            {
                this.nickNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string staffID
        {
            get
            {
                return this.staffIDField;
            }
            set
            {
                this.staffIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string depNameTH
        {
            get
            {
                return this.depNameTHField;
            }
            set
            {
                this.depNameTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string segNameTH
        {
            get
            {
                return this.segNameTHField;
            }
            set
            {
                this.segNameTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string positionNameTH
        {
            get
            {
                return this.positionNameTHField;
            }
            set
            {
                this.positionNameTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string depNameEN
        {
            get
            {
                return this.depNameENField;
            }
            set
            {
                this.depNameENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string segNameEN
        {
            get
            {
                return this.segNameENField;
            }
            set
            {
                this.segNameENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string positionNameEN
        {
            get
            {
                return this.positionNameENField;
            }
            set
            {
                this.positionNameENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string startDT
        {
            get
            {
                return this.startDTField;
            }
            set
            {
                this.startDTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string endDT
        {
            get
            {
                return this.endDTField;
            }
            set
            {
                this.endDTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string fullNameTH
        {
            get
            {
                return this.fullNameTHField;
            }
            set
            {
                this.fullNameTHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string fullNameEN
        {
            get
            {
                return this.fullNameENField;
            }
            set
            {
                this.fullNameENField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="hr.etda.or.th.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InquiryPersonnelInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<hr.etda.or.th.InquiryPersonnelInfoResponse> InquiryPersonnelInfoAsync(hr.etda.or.th.InquiryPersonnelInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InquiryPersonnelNewInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<hr.etda.or.th.InquiryPersonnelNewInfoResponse> InquiryPersonnelNewInfoAsync(hr.etda.or.th.InquiryPersonnelNewInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InquiryDepartmentMasterInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<hr.etda.or.th.InquiryDepartmentMasterInfoResponse> InquiryDepartmentMasterInfoAsync(hr.etda.or.th.InquiryDepartmentMasterInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InquirySegmentMasterInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<hr.etda.or.th.InquirySegmentMasterInfoResponse> InquirySegmentMasterInfoAsync(hr.etda.or.th.InquirySegmentMasterInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InquiryDepartmentSegmentMasterInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<hr.etda.or.th.InquiryDepartmentSegmentMasterInfoResponse> InquiryDepartmentSegmentMasterInfoAsync(hr.etda.or.th.InquiryDepartmentSegmentMasterInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquiryPersonnelInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquiryPersonnelInfo", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquiryPersonnelInfoRequestBody Body;
        
        public InquiryPersonnelInfoRequest()
        {
        }
        
        public InquiryPersonnelInfoRequest(hr.etda.or.th.InquiryPersonnelInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquiryPersonnelInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string staffName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string stafSurname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string staffStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string depID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string segID;
        
        public InquiryPersonnelInfoRequestBody()
        {
        }
        
        public InquiryPersonnelInfoRequestBody(string staffID, string staffName, string stafSurname, string staffStatus, string depID, string segID)
        {
            this.staffID = staffID;
            this.staffName = staffName;
            this.stafSurname = stafSurname;
            this.staffStatus = staffStatus;
            this.depID = depID;
            this.segID = segID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquiryPersonnelInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquiryPersonnelInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquiryPersonnelInfoResponseBody Body;
        
        public InquiryPersonnelInfoResponse()
        {
        }
        
        public InquiryPersonnelInfoResponse(hr.etda.or.th.InquiryPersonnelInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquiryPersonnelInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement InquiryPersonnelInfoResult;
        
        public InquiryPersonnelInfoResponseBody()
        {
        }
        
        public InquiryPersonnelInfoResponseBody(System.Xml.XmlElement InquiryPersonnelInfoResult)
        {
            this.InquiryPersonnelInfoResult = InquiryPersonnelInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquiryPersonnelNewInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquiryPersonnelNewInfo", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquiryPersonnelNewInfoRequestBody Body;
        
        public InquiryPersonnelNewInfoRequest()
        {
        }
        
        public InquiryPersonnelNewInfoRequest(hr.etda.or.th.InquiryPersonnelNewInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquiryPersonnelNewInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string staffID;
        
        public InquiryPersonnelNewInfoRequestBody()
        {
        }
        
        public InquiryPersonnelNewInfoRequestBody(string staffID)
        {
            this.staffID = staffID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquiryPersonnelNewInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquiryPersonnelNewInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquiryPersonnelNewInfoResponseBody Body;
        
        public InquiryPersonnelNewInfoResponse()
        {
        }
        
        public InquiryPersonnelNewInfoResponse(hr.etda.or.th.InquiryPersonnelNewInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquiryPersonnelNewInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public hr.etda.or.th.InquiryPersonnelNewInfoRS InquiryPersonnelNewInfoResult;
        
        public InquiryPersonnelNewInfoResponseBody()
        {
        }
        
        public InquiryPersonnelNewInfoResponseBody(hr.etda.or.th.InquiryPersonnelNewInfoRS InquiryPersonnelNewInfoResult)
        {
            this.InquiryPersonnelNewInfoResult = InquiryPersonnelNewInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquiryDepartmentMasterInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquiryDepartmentMasterInfo", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquiryDepartmentMasterInfoRequestBody Body;
        
        public InquiryDepartmentMasterInfoRequest()
        {
        }
        
        public InquiryDepartmentMasterInfoRequest(hr.etda.or.th.InquiryDepartmentMasterInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquiryDepartmentMasterInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string depID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string depName;
        
        public InquiryDepartmentMasterInfoRequestBody()
        {
        }
        
        public InquiryDepartmentMasterInfoRequestBody(string depID, string depName)
        {
            this.depID = depID;
            this.depName = depName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquiryDepartmentMasterInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquiryDepartmentMasterInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquiryDepartmentMasterInfoResponseBody Body;
        
        public InquiryDepartmentMasterInfoResponse()
        {
        }
        
        public InquiryDepartmentMasterInfoResponse(hr.etda.or.th.InquiryDepartmentMasterInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquiryDepartmentMasterInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement InquiryDepartmentMasterInfoResult;
        
        public InquiryDepartmentMasterInfoResponseBody()
        {
        }
        
        public InquiryDepartmentMasterInfoResponseBody(System.Xml.XmlElement InquiryDepartmentMasterInfoResult)
        {
            this.InquiryDepartmentMasterInfoResult = InquiryDepartmentMasterInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquirySegmentMasterInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquirySegmentMasterInfo", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquirySegmentMasterInfoRequestBody Body;
        
        public InquirySegmentMasterInfoRequest()
        {
        }
        
        public InquirySegmentMasterInfoRequest(hr.etda.or.th.InquirySegmentMasterInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquirySegmentMasterInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string segID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string segName;
        
        public InquirySegmentMasterInfoRequestBody()
        {
        }
        
        public InquirySegmentMasterInfoRequestBody(string segID, string segName)
        {
            this.segID = segID;
            this.segName = segName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquirySegmentMasterInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquirySegmentMasterInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquirySegmentMasterInfoResponseBody Body;
        
        public InquirySegmentMasterInfoResponse()
        {
        }
        
        public InquirySegmentMasterInfoResponse(hr.etda.or.th.InquirySegmentMasterInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquirySegmentMasterInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement InquirySegmentMasterInfoResult;
        
        public InquirySegmentMasterInfoResponseBody()
        {
        }
        
        public InquirySegmentMasterInfoResponseBody(System.Xml.XmlElement InquirySegmentMasterInfoResult)
        {
            this.InquirySegmentMasterInfoResult = InquirySegmentMasterInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquiryDepartmentSegmentMasterInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquiryDepartmentSegmentMasterInfo", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquiryDepartmentSegmentMasterInfoRequestBody Body;
        
        public InquiryDepartmentSegmentMasterInfoRequest()
        {
        }
        
        public InquiryDepartmentSegmentMasterInfoRequest(hr.etda.or.th.InquiryDepartmentSegmentMasterInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquiryDepartmentSegmentMasterInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string depID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string segID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string depName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string segName;
        
        public InquiryDepartmentSegmentMasterInfoRequestBody()
        {
        }
        
        public InquiryDepartmentSegmentMasterInfoRequestBody(string depID, string segID, string depName, string segName)
        {
            this.depID = depID;
            this.segID = segID;
            this.depName = depName;
            this.segName = segName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquiryDepartmentSegmentMasterInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquiryDepartmentSegmentMasterInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public hr.etda.or.th.InquiryDepartmentSegmentMasterInfoResponseBody Body;
        
        public InquiryDepartmentSegmentMasterInfoResponse()
        {
        }
        
        public InquiryDepartmentSegmentMasterInfoResponse(hr.etda.or.th.InquiryDepartmentSegmentMasterInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InquiryDepartmentSegmentMasterInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement InquiryDepartmentSegmentMasterInfoResult;
        
        public InquiryDepartmentSegmentMasterInfoResponseBody()
        {
        }
        
        public InquiryDepartmentSegmentMasterInfoResponseBody(System.Xml.XmlElement InquiryDepartmentSegmentMasterInfoResult)
        {
            this.InquiryDepartmentSegmentMasterInfoResult = InquiryDepartmentSegmentMasterInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceSoapChannel : hr.etda.or.th.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<hr.etda.or.th.ServiceSoap>, hr.etda.or.th.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hr.etda.or.th.InquiryPersonnelInfoResponse> hr.etda.or.th.ServiceSoap.InquiryPersonnelInfoAsync(hr.etda.or.th.InquiryPersonnelInfoRequest request)
        {
            return base.Channel.InquiryPersonnelInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<hr.etda.or.th.InquiryPersonnelInfoResponse> InquiryPersonnelInfoAsync(string staffID, string staffName, string stafSurname, string staffStatus, string depID, string segID)
        {
            hr.etda.or.th.InquiryPersonnelInfoRequest inValue = new hr.etda.or.th.InquiryPersonnelInfoRequest();
            inValue.Body = new hr.etda.or.th.InquiryPersonnelInfoRequestBody();
            inValue.Body.staffID = staffID;
            inValue.Body.staffName = staffName;
            inValue.Body.stafSurname = stafSurname;
            inValue.Body.staffStatus = staffStatus;
            inValue.Body.depID = depID;
            inValue.Body.segID = segID;
            return ((hr.etda.or.th.ServiceSoap)(this)).InquiryPersonnelInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hr.etda.or.th.InquiryPersonnelNewInfoResponse> hr.etda.or.th.ServiceSoap.InquiryPersonnelNewInfoAsync(hr.etda.or.th.InquiryPersonnelNewInfoRequest request)
        {
            return base.Channel.InquiryPersonnelNewInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<hr.etda.or.th.InquiryPersonnelNewInfoResponse> InquiryPersonnelNewInfoAsync(string staffID)
        {
            hr.etda.or.th.InquiryPersonnelNewInfoRequest inValue = new hr.etda.or.th.InquiryPersonnelNewInfoRequest();
            inValue.Body = new hr.etda.or.th.InquiryPersonnelNewInfoRequestBody();
            inValue.Body.staffID = staffID;
            return ((hr.etda.or.th.ServiceSoap)(this)).InquiryPersonnelNewInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hr.etda.or.th.InquiryDepartmentMasterInfoResponse> hr.etda.or.th.ServiceSoap.InquiryDepartmentMasterInfoAsync(hr.etda.or.th.InquiryDepartmentMasterInfoRequest request)
        {
            return base.Channel.InquiryDepartmentMasterInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<hr.etda.or.th.InquiryDepartmentMasterInfoResponse> InquiryDepartmentMasterInfoAsync(string depID, string depName)
        {
            hr.etda.or.th.InquiryDepartmentMasterInfoRequest inValue = new hr.etda.or.th.InquiryDepartmentMasterInfoRequest();
            inValue.Body = new hr.etda.or.th.InquiryDepartmentMasterInfoRequestBody();
            inValue.Body.depID = depID;
            inValue.Body.depName = depName;
            return ((hr.etda.or.th.ServiceSoap)(this)).InquiryDepartmentMasterInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hr.etda.or.th.InquirySegmentMasterInfoResponse> hr.etda.or.th.ServiceSoap.InquirySegmentMasterInfoAsync(hr.etda.or.th.InquirySegmentMasterInfoRequest request)
        {
            return base.Channel.InquirySegmentMasterInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<hr.etda.or.th.InquirySegmentMasterInfoResponse> InquirySegmentMasterInfoAsync(string segID, string segName)
        {
            hr.etda.or.th.InquirySegmentMasterInfoRequest inValue = new hr.etda.or.th.InquirySegmentMasterInfoRequest();
            inValue.Body = new hr.etda.or.th.InquirySegmentMasterInfoRequestBody();
            inValue.Body.segID = segID;
            inValue.Body.segName = segName;
            return ((hr.etda.or.th.ServiceSoap)(this)).InquirySegmentMasterInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hr.etda.or.th.InquiryDepartmentSegmentMasterInfoResponse> hr.etda.or.th.ServiceSoap.InquiryDepartmentSegmentMasterInfoAsync(hr.etda.or.th.InquiryDepartmentSegmentMasterInfoRequest request)
        {
            return base.Channel.InquiryDepartmentSegmentMasterInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<hr.etda.or.th.InquiryDepartmentSegmentMasterInfoResponse> InquiryDepartmentSegmentMasterInfoAsync(string depID, string segID, string depName, string segName)
        {
            hr.etda.or.th.InquiryDepartmentSegmentMasterInfoRequest inValue = new hr.etda.or.th.InquiryDepartmentSegmentMasterInfoRequest();
            inValue.Body = new hr.etda.or.th.InquiryDepartmentSegmentMasterInfoRequestBody();
            inValue.Body.depID = depID;
            inValue.Body.segID = segID;
            inValue.Body.depName = depName;
            inValue.Body.segName = segName;
            return ((hr.etda.or.th.ServiceSoap)(this)).InquiryDepartmentSegmentMasterInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://hr.etda.or.th/webservice-production/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://hr.etda.or.th/webservice-production/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
